### ISSUE TITLE
_nav.html 내용 확인 부탁드려요

### ISSUE THREAD

**Issue by liza0525** [liza0525/realcollabo#4]
title은 '정오의 만찬'
메뉴는 팀원 소개/프로젝트 소개/역할 분담
이렇게 하려고 하는데 괜찮은가요?

+_nav.html 파일로 만드려고 하는데
혹시 템플릿 상속하실건지 말씀 부탁드립니다.

**Comment by ohsean93** [comment]
음 그것보다는 카드에 모든 정보를 넣는 것은 어떨까요? 이건 메인 페이지에 들어가는 정보라고 생각해서요!

메뉴는 앞으로의 다른 프로젝트를 (예를 들면 영화소개라던가 영화소개라던가 그런것들이요!)넣으면 좋을거 같아요(비록 연습이지만요!)

**Comment by liza0525** [comment]
그럼 (연습이긴 하지만 ㅋㅋ) 영화 소개/영화 정보 등록 일단 두 개만 넣어보겠습니다!

**Comment by ohsean93** [comment]
넵 더 변경할 것이 없으면 30분뒤에 이슈 닫아 주실수 있으신가요??
